/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aiju_updatejni_UpdateJniUtils */

#ifndef _Included_com_aiju_updatejni_UpdateJniUtils
#define _Included_com_aiju_updatejni_UpdateJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aiju_updatejni_UpdateJniUtils
 * Method:    applyPatchToOldApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_seed_updatejni_UpdateJniUtils_applyPatchToOldApk
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
